services:
  backend:
    build: ./backend
    environment:
      - SAM_VERSION=small
    volumes:
      - freeze-me-videos:/app/src/videos
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  freeze-me-videos:
